// One shared Postgres container, one database per checkout.
//
// `compose.yml` pins its project name to `bebop`, so `docker compose up` is idempotent
// from any checkout and every worktree on the machine shares the same container. This
// script gives the current checkout its own database on that container and records both
// URLs in the gitignored `mise.local.toml`, which mise loads into the shell:
//
//   vp run dev:db
//
// The database name derives from the checkout's directory: the main checkout uses the
// seeded `bebop` database, a worktree uses `bebop_<sanitized basename>`. Override with
// `BEBOP_DEV_DATABASE_NAME` when the derivation is not what you want.
//
// The URLs must reach the process environment rather than a file a child loads on its
// own: the `test` and `local-system` tasks list `BEBOP_TEST_DATABASE_URL` in their cache
// key, so `vp` itself has to see its value. mise sets real process env, which is why it
// is the file of record instead of `.env`.

import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { basename, join } from "node:path";

const ADMIN_DATABASE = "bebop";

function run(program: string, args: readonly string[]): string {
  try {
    return execFileSync(program, args, { encoding: "utf8", stdio: ["ignore", "pipe", "pipe"] }).trim();
  } catch (error) {
    const stderr =
      error !== null && typeof error === "object" && "stderr" in error
        ? String((error as { stderr: unknown }).stderr)
        : "";
    const detail = stderr ? `\n${stderr}` : "";
    throw new Error(`Command failed: ${program} ${args.join(" ")}${detail}`, { cause: error });
  }
}

function checkoutRoot(): string {
  try {
    return run("git", ["rev-parse", "--show-toplevel"]);
  } catch {
    throw new Error("not a git checkout — run this from inside the repository");
  }
}

function composePostgres(args: readonly string[]): string {
  // `docker compose exec` reads `compose.yml` from the current directory and resolves the
  // project by its pinned name, so this reaches the shared container from any checkout.
  return run("docker", ["compose", "exec", "-T", "postgres", ...args]);
}

function containerAcceptsConnections(): boolean {
  try {
    composePostgres(["pg_isready", "-U", "bebop", "-d", ADMIN_DATABASE]);
    return true;
  } catch {
    return false;
  }
}

function ensureContainer(): void {
  if (containerAcceptsConnections()) return;
  // The container is not reachable — start it. The pinned project name makes this
  // idempotent and attaches to the existing container rather than starting a second one.
  run("docker", ["compose", "up", "-d", "--wait", "postgres"]);
}

const NAME_PATTERN = /^[a-z0-9_]+$/;

function devDatabaseName(): string {
  const override = process.env.BEBOP_DEV_DATABASE_NAME;
  if (override !== undefined && override.length > 0) {
    if (!NAME_PATTERN.test(override)) {
      throw new Error(`BEBOP_DEV_DATABASE_NAME must match ${NAME_PATTERN} — got: ${override}`);
    }
    return override;
  }
  const directory = basename(checkoutRoot());
  // The main checkout's directory is `bebop`, which is the database `POSTGRES_DB` seeds.
  return directory === ADMIN_DATABASE ? ADMIN_DATABASE : sanitize(directory);
}

function sanitize(identifier: string): string {
  const cleaned = identifier
    .toLowerCase()
    .replaceAll(/[^a-z0-9_]+/g, "_")
    .replaceAll(/_+/g, "_")
    .replace(/^_+|_+$/g, "");
  // Postgres identifiers are truncated at 63 bytes; the `bebop_` prefix keeps the name
  // out of reserved-word territory and the slice keeps it short enough to survive.
  return `bebop_${cleaned}`.slice(0, 63);
}

function databaseExists(name: string): boolean {
  // The name is script-derived and sanitized, so embedding it in SQL is safe.
  const result = composePostgres([
    "psql",
    "-U",
    "bebop",
    "-d",
    ADMIN_DATABASE,
    "-tAc",
    `SELECT 1 FROM pg_database WHERE datname = '${name}'`,
  ]);
  return result === "1";
}

function ensureDatabase(name: string): void {
  if (databaseExists(name)) return;
  composePostgres(["psql", "-U", "bebop", "-d", ADMIN_DATABASE, "-c", `CREATE DATABASE "${name}"`]);
}

function writeMiseLocal(databaseUrl: string, adminUrl: string): void {
  const contents = [
    "# Generated by scripts/dev-db.ts — local to this checkout; do not commit.",
    "[env]",
    `BEBOP_DATABASE_URL = "${databaseUrl}"`,
    `BEBOP_TEST_DATABASE_URL = "${adminUrl}"`,
    "",
  ].join("\n");
  writeFileSync(join(checkoutRoot(), "mise.local.toml"), contents);
}

function trustMiseConfig(): boolean {
  try {
    run("mise", ["trust"]);
    return true;
  } catch {
    return false;
  }
}

const name = devDatabaseName();
ensureContainer();
ensureDatabase(name);

const adminUrl = `postgres://bebop:bebop@127.0.0.1:5433/${ADMIN_DATABASE}`;
const databaseUrl = `postgres://bebop:bebop@127.0.0.1:5433/${name}`;

writeMiseLocal(databaseUrl, adminUrl);

const exports = [`export BEBOP_DATABASE_URL='${databaseUrl}'`, `export BEBOP_TEST_DATABASE_URL='${adminUrl}'`].join(
  "\n",
);

if (trustMiseConfig()) {
  process.stdout.write(
    [
      `dev database: ${name}`,
      `wrote mise.local.toml — the variables apply in a new shell, or after cd'ing out and back.`,
      `  ${exports}`,
      "",
    ].join("\n"),
  );
} else {
  process.stdout.write(
    [
      `dev database: ${name}`,
      `mise was not found — source these in the current shell, or install mise and re-run:`,
      `  ${exports}`,
      "",
    ].join("\n"),
  );
}
